"""add Department

Revision ID: 95912af78eaf
Revises: 06f59b811afe
Create Date: 2025-03-27 11:12:38.983984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95912af78eaf'
down_revision = '06f59b811afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###